name: Deploy amarpet application on staging server

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deployment process
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_ROOT_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/redis-pub-sub/laravel-redis-pub
            php artisan down
            git fetch --all
            git checkout master
            composer update -o -n --no-dev
            php artisan migrate
            php artisan optimize
            php artisan up