name: Deploy amarpet application on staging server

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deployment process
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_ROOT_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/laravel-redis-publisher
            make pull
            make stop
            make start
            make down
            make migrate
            make optimize
            make up
            make unused-images-remove
